### ISSUE TITLE
Orient arrow to point forward all the time

### ISSUE THREAD

**Issue by Byroni** [Bananapen/Adv-Game-Design#22]
This one should be pretty easy; I have it set to orient itself to world space, instead of the local space, so the arrows always point towards one direction no matter where you shoot them from. Will fix this soon, probably when we have our actual arrow models.

**Comment by LupinWonse** [comment]
#48 merge request implements a solution for the initial orientation.

**Comment by LupinWonse** [comment]
#49 solves this problem, I think it is safe to close this issue.
