### ISSUE TITLE
Arrow physics a little off

### ISSUE THREAD

**Issue by Byroni** [Bananapen/Adv-Game-Design#46]
It seems that arrows transfer momentum to the blocks it hits, as expected, but there's an issue. The arrows continue to 'push' the block, until it destroys itself (Arrows have a Destroy (this, 2) method).

For example, if an arrow has a velocity of 10, and it hits a block, the block will then have a velocity of 10 until the arrow is destroyed. The momentum doesn't dissipate over time when it goes into the blocks.

It's like the arrows have rockets at the end of them that continuously push. If you pinned a block in the air against a wall, it will stay pinned by the constant force of the arrow.

**Comment by LupinWonse** [comment]
Caused by collisions still happening after the arrow is stuck (block set as parent). Disabling collider fixes the problem. Sovled in the mentioned merge request.
