### ISSUE TITLE
Sluggish arrow movement when player is also moving

### ISSUE THREAD

**Issue by LupenWonse** [Bananapen/Adv-Game-Design#71]
When the player shoots an arrow and watches while strafing it is very obvious that the arrow is jumping from point to point.
I assume this has to do with the arrow movement and ray cast. Will attempt a fix.

**Comment by LupenWonse** [comment]
Don't think it has to do anything with the recasting. Will test on my pc to see if FPS is an issue.
If anyone can replicate please let me know

**Comment by Byroni** [comment]
I tested it on my mac and I can kind of see it. I'm not sure, it may just be psycho-symatic just because you mentioned it. On my pc it's completely fine. I don't think it's a mac vs pc thing though; My PC is much stronger and it may just be a matter of performance.

**Comment by LupenWonse** [comment]
This is for sure happening because character movement is performed on Update() and arrow moves with Rigidbody (FixedUpdate). There are several solutions that can be applied
- Move character in FixedUpdate (movement become somewhat choppy)
- Move the arrow with script and not use physics (requires more code)
- Enable interpolation on character (we need a rigidbody based character)
- Enable interpolation on the arrows (computationally expensive)
For now I am implementing the last option, which seems to be the simplest and most complete solution for this problem.
